import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUsuarioRelationToGalerias1756656608042 implements MigrationInterface {
    name = 'AddUsuarioRelationToGalerias1756656608042'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "artistas" DROP CONSTRAINT "artistas_id_galeria_fkey"`);
        await queryRunner.query(`ALTER TABLE "obras" DROP CONSTRAINT "obras_id_artista_fkey"`);
        await queryRunner.query(`ALTER TABLE "obras" DROP CONSTRAINT "obras_id_galeria_fkey"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP CONSTRAINT "exposiciones_id_artista_fkey"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP CONSTRAINT "exposiciones_id_galeria_fkey"`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP CONSTRAINT "fk_galeria_usuario"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_id_galeria_fkey"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_rol_check"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_descuento_check"`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id_usuario" SERIAL NOT NULL, "nombre" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "rol" character varying NOT NULL DEFAULT 'usuario', CONSTRAINT "UQ_2863682842e688ca198eb25c124" UNIQUE ("email"), CONSTRAINT "PK_dd52716c2652e0e23c15530c695" PRIMARY KEY ("id_usuario"))`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "precio"`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "disponible"`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "id_galeria"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP COLUMN "fecha_inicio"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP COLUMN "fecha_fin"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "fecha_registro"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "descuento"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "fecha_inicio"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "fecha_fin"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "id_galeria"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "precio" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "activa" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "galeriaIdGaleria" integer`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "obraIdObra" integer`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP COLUMN "biografia"`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD "biografia" character varying`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP COLUMN "estilo"`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD "estilo" character varying`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "titulo"`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "titulo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "obras" ALTER COLUMN "id_artista" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP COLUMN "titulo"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD "titulo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_email_key"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "rol"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "rol" character varying NOT NULL DEFAULT 'usuario'`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "telefono" character varying`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "direccion" character varying`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "ciudad"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "ciudad" character varying`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "web"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "web" character varying`);
        await queryRunner.query(`ALTER TABLE "galerias" ALTER COLUMN "usuario_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD CONSTRAINT "FK_1841448a19a87d38e747b4962c3" FOREIGN KEY ("id_galeria") REFERENCES "galerias"("id_galeria") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "obras" ADD CONSTRAINT "FK_3d8363c5c68ff39d642ea8438f9" FOREIGN KEY ("id_artista") REFERENCES "artistas"("id_artista") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "obras" ADD CONSTRAINT "FK_f08bae5547aaa7df83282b4c5ce" FOREIGN KEY ("id_exposicion") REFERENCES "exposiciones"("id_exposicion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD CONSTRAINT "FK_3366d715cf1748b6be6c2b1b7b5" FOREIGN KEY ("id_galeria") REFERENCES "galerias"("id_galeria") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD CONSTRAINT "FK_f95ea86cc5759e1b51827b0e14d" FOREIGN KEY ("id_artista") REFERENCES "artistas"("id_artista") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD CONSTRAINT "FK_6270efa101f98e232457af70c5d" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "FK_138a679ba54a109074d34476ab0" FOREIGN KEY ("galeriaIdGaleria") REFERENCES "galerias"("id_galeria") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "FK_17d4587e919a1c41133e2d202ea" FOREIGN KEY ("obraIdObra") REFERENCES "obras"("id_obra") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "FK_17d4587e919a1c41133e2d202ea"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "FK_138a679ba54a109074d34476ab0"`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP CONSTRAINT "FK_6270efa101f98e232457af70c5d"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP CONSTRAINT "FK_f95ea86cc5759e1b51827b0e14d"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP CONSTRAINT "FK_3366d715cf1748b6be6c2b1b7b5"`);
        await queryRunner.query(`ALTER TABLE "obras" DROP CONSTRAINT "FK_f08bae5547aaa7df83282b4c5ce"`);
        await queryRunner.query(`ALTER TABLE "obras" DROP CONSTRAINT "FK_3d8363c5c68ff39d642ea8438f9"`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP CONSTRAINT "FK_1841448a19a87d38e747b4962c3"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "galerias" ALTER COLUMN "usuario_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "web"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "web" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "ciudad"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "ciudad" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "direccion" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "telefono" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "email" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "galerias" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD "nombre" character varying(150) NOT NULL DEFAULT 'Nombre por defecto'`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "rol"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "rol" character varying(20) DEFAULT 'usuario'`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "email" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "nombre" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "exposiciones" DROP COLUMN "titulo"`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD "titulo" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "obras" ALTER COLUMN "id_artista" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "obras" DROP COLUMN "titulo"`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "titulo" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP COLUMN "estilo"`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD "estilo" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP COLUMN "biografia"`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD "biografia" text`);
        await queryRunner.query(`ALTER TABLE "artistas" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD "nombre" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "obraIdObra"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "galeriaIdGaleria"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "activa"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "precio"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "id_galeria" integer`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "fecha_fin" date`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "fecha_inicio" date`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "descuento" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "codigo" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "fecha_registro" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD "fecha_fin" date`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD "fecha_inicio" date`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "id_galeria" integer`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "disponible" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "obras" ADD "precio" numeric(10,2)`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_descuento_check" CHECK (((descuento > (0)::numeric) AND (descuento <= (100)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_rol_check" CHECK (((rol)::text = ANY (ARRAY['ADMIN'::text, 'GALLERY'::text, 'USER'::text, 'ARTIST'::text])))`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_id_galeria_fkey" FOREIGN KEY ("id_galeria") REFERENCES "galerias"("id_galeria") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "galerias" ADD CONSTRAINT "fk_galeria_usuario" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD CONSTRAINT "exposiciones_id_galeria_fkey" FOREIGN KEY ("id_galeria") REFERENCES "galerias"("id_galeria") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exposiciones" ADD CONSTRAINT "exposiciones_id_artista_fkey" FOREIGN KEY ("id_artista") REFERENCES "artistas"("id_artista") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "obras" ADD CONSTRAINT "obras_id_galeria_fkey" FOREIGN KEY ("id_galeria") REFERENCES "galerias"("id_galeria") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "obras" ADD CONSTRAINT "obras_id_artista_fkey" FOREIGN KEY ("id_artista") REFERENCES "artistas"("id_artista") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artistas" ADD CONSTRAINT "artistas_id_galeria_fkey" FOREIGN KEY ("id_galeria") REFERENCES "galerias"("id_galeria") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
